#!/usr/bin/env bash
# (one can also call the js script directly
# but node still requires it to have the .js extension
# thus this wrap makes it a bit more comfy)

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
# echo "Single run of test scenario"

# clear screen REF stackoverflow.com/a/37778152
echo -e "\e[2J\e[H"

# sync, and wipe line (KISS)
source $scriptDir/sync-testfiles
echo -e "\e[1A\e[2m\e[34m________________________________________________\e[0m"

echo "photo (verbose+specific) ========================================="
/usr/bin/node $scriptDir/src/main.js -l sanitize --stats "$PWD/TEST-FOLDER"
