#!/usr/bin/env bash
# (one can also call the js script directly
# but node still requires it to have the .js extension
# thus this wrap makes it a bit more comfy)

cd /common/images
echo 'syncing... ====================================='

rsync -rtogp --exclude='.git' --inplace --delete \
  /common/images/ORIG-TEST-FOLDER/ \
  /common/images/TEST-FOLDER
