#!/usr/bin/env bash

echo '\nshow local → npm-global (expected: 2 entries) ==============='
ls -lar ./node_modules/ ./node_modules/@nocke | grep '../'

echo -e '\nshow npm-global →  target ================================'
ls -lar `npm config get prefix`/lib/node_modules | grep '../'
echo ''
ls -lar `npm config get prefix`/lib/node_modules/@nocke | grep '../'
