#!/usr/bin/env bash
# (one can also call the js script directly
# but node still requires it to have the .js extension
# thus this wrap makes it a bit more comfy)

# cd /common/images
echo 'syncing... ====================================='

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
SRC="$scriptDir/../node_modules/photo-testfiles/ørig"
DEST="$scriptDir/../TEST-FOLDER"
echo SRC $SRC "xxx" DEST $DEST

if [ ! -d "$SRC" ]; then
  echo "\nError: testfile source directory $SRC does not exist, did you do ‘npm install’?"
  exit 1
fi

rsync -rtogp --exclude='.git' --inplace --delete "$SRC/" "$DEST"

if [ $? -ne 0 ]; then
  echo "Error: rsync operation failed"
  exit 1
fi

diff -rq "$SRC" "$DEST"

# Check if there are any differences
if [ $? -ne 0 ]; then
  echo "Error: Differences found between $SRC and $DEST"
  exit 1
fi
